version: '3'

services:
  app:
    image: embraslabs/ruby:2.5.1
    stdin_open: true
    depends_on:
      - db
    volumes:
      - .:/app
      - gems:/.gems

  db:
    image: jacobalberty/firebird:2.5.8-ss
    environment:
      - ISC_PASSWORD=masterkey
      - TZ=America/Sao_Paulo
    volumes:
      - firebird:/firebird
      - ./spec/db/example.fdb:/firebird/data/test.fdb
      - ./db/example.fdb:/firebird/data/example.fdb
    ports:
      - "5050:3050"

volumes:
  gems:
  firebird:
